version: "3.2"

networks:
  infra:
    external: true
      
services:
  rauhala:
    image: ghcr.io/mirorauhala/rauhala.dev:latest
    restart: 'unless-stopped'
    container_name: rauhala
    networks:
      - infra
